blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns =[
    path('',views.index,name='index'),
    path('article/<slug:slug>',views.page,name='page'),
    path('category/<slug:slug>',views.category,name='category'),
    path('new/',views.new,name='new'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from extensions.utils import jalali_convert
class Article_manager(models.Manager):
    def published(self):
        return self.filter(status='p')
class Category(models.Model):
    title=models.CharField(max_length=20,verbose_name='دسته بندی ')
    status=models.BooleanField(default=True,verbose_name='وضعیت ')
    slug=models.SlugField(max_length=12,unique=True,verbose_name='شماره ')

    class Meta:
        verbose_name_plural='دسته بندی های من '
    def __str__(self):
        return self.title


class Artile(models.Model):
    STATUS_CHOIC=(
        ('l','چاپ شده'),('n','چاپ نشده '),
    )
    name=models.CharField(max_length=20,verbose_name='اسم نویسنده ')
    category=models.ManyToManyField(Category,verbose_name='دسته بندی',related_name='article')
    title=models.CharField(max_length=30,verbose_name='نام عنوان')
    image = models.ImageField(upload_to='images',verbose_name='تصویر')
    description=models.TextField(verbose_name='ایجاد متن')
    status=models.CharField(max_length=1,choices=STATUS_CHOIC,verbose_name='وضعیت')
    publish=models.DateTimeField(default=timezone.now,verbose_name='زمان انتشار')

    slug=models.SlugField(max_length=12,unique=True)
    class Meta:
        verbose_name_plural='نظرات من'
        ordering=['-publish']

    def __str__(self):
        return self.title
    def jalali_publish(self):
        return jalali_convert(self.publish)

    objects=Article_manager()
class testy(models.Model):
    test_passage=models.CharField(max_length=16,null=True,blank=False)
    Username=models.ForeignKey(User,null=True,related_name='username')
    slug=models.SlugField(unique=True)
    

blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render,get_object_or_404
from .models import Artile,Category
def index(request):
    articles_list=Artile.objects.published()
    paginator = Paginator(articles_list, 3)
    page = request.GET.get('page')
    article = paginator.get_page(page)
    context={
        'article':article,
        'category': Category.objects.all
    }

    return render (request,'blog/index.html',context)
def page(request,slug):
    context={
        'articles':get_object_or_404(Artile,slug=slug,status='p'),
    }
    return render(request,'blog/page.html',context)
def category(request,slug):
    context={
        'category': get_object_or_404(Category, slug=slug,status='True'),
    }
    return render(request,'blog/category.html',context)

def new(request):
    context={
        'new':Artile.objects.all
    }
    return render(request,'blog/new.html')

blog/templates/blog/base.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> حوادث{% block title%}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="static/blog/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="static/blog/https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="static/blog/https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="static/blog/css/styles.css" rel="stylesheet" />
        <link href="static/blog/css/rtl.css" rel="stylesheet" />

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#" style="color:orange;font-size:20px;"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>

            </div>
        </nav>
        {% block main %}
        {% endblock %}
        <!-- Footer-->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; Your Website 2021</p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="static/blog/https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="static/blog/https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="static/blog/js/scripts.js"></script>
    </body>
</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% block title %} |{{article.title}} {% endblock %}
{% block main %}
      <!-- Page Header-->
        <header class="masthead" style="background-image: url('static/blog/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                         <h3> {{article.title}}  </h3>
                        <div class="site-heading">
                            <h1 style="color:red;font-size:26;">وبلاگ من </h1>
                            <span class="subheading"style="color:black;font-weight:bold;font-size:30px;">زمانی برای آرامش </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                 {% for articles in category.article.published %}
                    <div class="post-preview">
                        <a href="{% url 'blog:page' articles.slug  %}">
                            <h2 class="post-title">{{articles.title}}</h2>
                            <h3 class="post-subtitle">{{articles.description | truncatewords:10}}</h3>
                        </a>
                        <p class="post-meta">
                            نوشته شده توسط
                            <a href="#!">{{articles.jalali_publish}}</a>

                        </p>
                        <div>
                          {% for cat in articles.category.all %}
                            <a href="#">#{{cat.title}}</a>
                          {% endfor %}
                        </div>

                    </div>
                 {%endfor %}
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %} |{{article.title}} {% endblock %}
{% block main %}
      <!-- Page Header-->
         <p>Hi </p>
         <div>
             <ul>
                 <li>
                     <a href="#"></a>
                 </li>
             </ul>
         </div>
        <header class="masthead" style="background-image: url('static/blog/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1 style="color:red;font-size:26;">جنگویی</h1>
                            <span class="subheading"style="color:black;font-weight:bold;font-size:30px;">زمانی برای آرامش </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                 {% for articles in article %}
                    <div class="post-preview">
                        <a href="{% url 'blog:page' articles.slug  %}">
                            <h2 class="post-title">{{articles.time}}</h2>
                            <h3 class="post-subtitle">{{articles.description | truncatewords:10}}</h3>
                        </a>
                        <p class="post-meta">
                            محمدرضا نوشته
                            <a href="#!">{{articles.jalali_publish}}</a>

                        </p>
                        <div>
                          {% for cat in articles.category.all %}
                            <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                          {% endfor %}
                        </div>

                    </div>
                 {%endfor %}
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4">
                       {% if article.has_previous %}

                          <a class="btn btn-primary text-uppercase" href="#!">پست های قدیمی </a>
                       {%endif%}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}